version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: cosmic_void_auth_service_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cosmic_void_auth_service_db
    ports:
      - '5003:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    container_name: cosmic_void_auth_service_test_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cosmic_void_auth_service_test_db
    ports:
      - '6003:5432'
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    restart: 'no'
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  pgdata:
  test_pgdata:
  redis_data:
