version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: cosmic_void_example_service_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cosmic_void_example_service_db
    ports:
      - "5110:5432"
    volumes:
      - cosmic_void_example_service_pgdata:/var/lib/postgresql/data

volumes:
  cosmic_void_example_service_pgdata:
  cosmic_void_example_service_test_pgdata:
